### ISSUE TITLE
Add Twitter social login

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#228] opened 2015-09-25 16:10 UTC
Adding social logins may make it less of a hurdle for people to login and engage.

I just found another tutorial to help with this: https://www.digitalocean.com/community/tutorials/how-to-configure-devise-and-omniauth-for-your-rails-application

This code will help to deal with users who login with multiple social logins (assuming both accounts have the same email address): http://sourcey.com/rails-4-omniauth-using-devise-with-twitter-facebook-and-linkedin/

**Comment by campgurus** [comment] 2015-09-26 12:10
here is a link to our Twitter App: https://apps.twitter.com/app/8570608/show

**Comment by trystant** [comment] 2015-09-26 12:26
There's material in support of as well as against social logins for multiple reasons. I think that we should consider that before going down this road:

1. Privacy; people may not want Facebook or Twitter to know they've logged into EBW.
2. [MailChimp](https://blog.mailchimp.com/social-login-buttons-arent-worth-it/)  and [others](http://www.emarketer.com/Article/Privacy-Concerns-Keep-Users-Away-Social-Sign-In/1009613) have noted privacy concerns and other reasons why people do NOT use social login.

I'm personally opposed to it myself, and want to see more data that proves this'll be helpful, not just a supposition.

**Comment by campgurus** [comment] 2015-09-26 17:57
Social login would be an option, not required. Are you saying the mere
presence of a social login option would be harmful?

**Comment by trystant** [comment] 2015-10-04 18:55
It could be, as described in the articles I used to bolster my position. The article is worth a read in order to have a more detailed understanding of the factors involved.

**Comment by trystant** [comment] 2016-05-11 00:17
Is this a duplicate of #491 ?

**Comment by campgurus** [comment] 2016-05-11 00:18
no.  this is for oauth authentication via twitter for people who want to login with Twitter instead of email/password.

**Comment by trystant** [comment] 2020-06-06 22:12
I'm closing this ticket for now.

**Closed by trystant** 2020-06-06 22:12 UTC
