### ISSUE TITLE
Add RSpec to test followers email

### ISSUE THREAD

**Issue by campgurus** [EBWiki/EBWiki#630] opened 2016-06-20 13:56 UTC
so far I am having trouble with the multiple users aspect of this test it seems.

This short tutorial post seems right, but I still can't get the test to register that two emails have been sent:

http://vicfriedman.github.io/blog/2013/08/05/how-to-write-rspec-mailer-tests/

I am trying this test:

```
describe 'send_followers_email' do
    ActionMailer::Base.delivery_method = :test
    ActionMailer::Base.perform_deliveries = true
    ActionMailer::Base.deliveries = []
    let(:user1) { mock_model User, name: 'John', email: 'john@email.com', all_following: [User.new] }
    let(:user2) { mock_model User, name: 'Dean', email: 'dean@email.com', all_following: [User.new] }
    users = [:user1, :user2]
    let(:article) {mock_model Article, title: 'John Smith', content: 'some content', state_id: 33}
    let(:mail) { UserNotifier.send_followers_email(users, article) }


    it "#send_followers_email should notify both users" do
      expect(ActionMailer::Base.deliveries.count).to eq(2)
      expect(ActionMailer::Base.deliveries[0].to).to include(user1.email)
      expect(ActionMailer::Base.deliveries[1].to).to include(user2.email)
    end
```

the result is:

`````` Failures:

  1) UserNotifier send_followers_email #send_followers_email should notify both users
     Failure/Error: expect(ActionMailer::Base.deliveries.count).to eq(2)

       expected: 2
            got: 0

       (compared using ==)
     # ./spec/mailers/user_notifier_spec.rb:59:in `block (3 levels) in <top (required)>'
     # ./spec/rails_helper.rb:67:in `block (3 levels) in <top (required)>'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/generic/base.rb:15:in `cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/base.rb:92:in `cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:86:in `block (2 levels) in cleaning'
     # ./.bundle/gems/ruby/2.3.0/gems/database_cleaner-1.3.0/lib/database_cleaner/configuration.rb:87:in `cleaning'
     # ./spec/rails_helper.rb:66:in `block (2 levels) in <top (required)>'

Finished in 1.29 seconds (files took 8.82 seconds to load)
9 examples, 1 failure```
``````

**Comment by rlgreen91** [comment] 2018-03-02 07:53
Closed as a duplicate of #1121

**Closed by rlgreen91** 2018-03-02 07:53 UTC
Labels: RSpec, testing
